<a href="https://colab.research.google.com/github/seankimblue/hello-world/blob/master/Broadcasting_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [0]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [0]:
percentage = 100 * A / cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [0]:
a = np.random.randn(5)
print(a)

[-0.83664922  0.63647853 -0.67845042 -0.24738253  1.51825075]


In [0]:
print(a.shape)

(5,)


In [0]:
print(a.T)

[-0.83664922  0.63647853 -0.67845042 -0.24738253  1.51825075]


In [0]:
print(np.dot(a,a.T))

3.931665260778561


In [0]:
b = np.random.randn(5,1)
print(b)
print(b.shape)

[[ 0.48041653]
 [ 0.61409553]
 [-0.27553827]
 [ 1.2872173 ]
 [-0.84056229]]
(5, 1)


In [0]:
print(b.T)

[[ 0.48041653  0.61409553 -0.27553827  1.2872173  -0.84056229]]


In [0]:
print(np.dot(b,b.T))

[[ 0.23080004  0.29502164 -0.13237314  0.61840047 -0.40382002]
 [ 0.29502164  0.37711331 -0.16920682  0.79047439 -0.51618554]
 [-0.13237314 -0.16920682  0.07592134 -0.35467763  0.23160708]
 [ 0.61840047  0.79047439 -0.35467763  1.65692839 -1.08198633]
 [-0.40382002 -0.51618554  0.23160708 -1.08198633  0.70654497]]


In [0]:
a=a.reshape((5,1))
print(a)
print(a.shape)

[[-0.83664922]
 [ 0.63647853]
 [-0.67845042]
 [-0.24738253]
 [ 1.51825075]]
(5, 1)
